### ISSUE TITLE
nodes names

### ISSUE THREAD

**Issue by woodyjon** [turtlecoin/turtlecoin-nodes-json#29]
An idea:
Would it be possible to review (and improve) the names given to the nodes, so that they are a bit more descriptive and not duplicated, so that I can list the names in Nest instead of the urls?
For example, avoid multiple "EU".

**Comment by woodyjon** [comment]
And accept PR only if the name is different from existing and descriptive enough.
Just proposing...

**Comment by brandonlehmann** [comment]
This makes sense to me.

**Comment by woodyjon** [comment]
Obviously, if a node operator wants, he can use its url for the name.

**Comment by brandonlehmann** [comment]
Added tests via https://github.com/turtlecoin/turtlecoin-nodes-json/commit/d2056c39481126f9d5df8a60f53038be0f6baaa0 to check for duplicate names. Awaiting Travis-CI activation. Considered complete.

**Comment by brandonlehmann** [comment]
Expect the first tests to fail

```
> turtlecoin-nodes-json@0.0.1 test D:\Data\Desktop\devbox\turtlecoin-nodes-json
> node tests/checkForDuplicates.js

ASIA
CHINA-ASIA
CHRISCRYPTO
Daemon.Turtle.Link
D. Smasher's Node
Dela Turtle EU
EU
EU
assert.js:42
  throw new errors.AssertionError({
  ^

AssertionError [ERR_ASSERTION]: false == true
    at Object.<anonymous> (D:\Data\Desktop\devbox\turtlecoin-nodes-json\tests\checkForDuplicates.js:11:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
npm ERR! Test failed.  See above for more details.
```

**Comment by woodyjon** [comment]
nice @brandonlehmann
